# Generated by Django 4.1.2 on 2025-01-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DaySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("was_active", models.BooleanField()),
                ("activity_name", models.CharField(max_length=250)),
                ("activity_quantity", models.FloatField()),
                ("activity_unit", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("dessert", "Dessert"),
                            ("supper", "Supper"),
                            ("snack", "Snack"),
                            ("drink", "Drink"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=25)),
                ("calories", models.IntegerField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="tracker.daysummary",
                    ),
                ),
            ],
        ),
    ]
