# Generated by Django 4.1.2 on 2025-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="daysummary",
            name="activity_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="daysummary",
            name="activity_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="daysummary",
            name="activity_unit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="daysummary",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="unit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
