# Generated by Django 4.1.2 on 2025-03-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_trackerprofile_daysummary_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysummary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.trackerprofile"
            ),
        ),
    ]
