# Generated by Django 4.1.2 on 2025-03-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_daysummary_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=25, null=True)),
                ("arm", models.FloatField(blank=True, null=True)),
                ("chest", models.FloatField(blank=True, null=True)),
                ("waist", models.FloatField(blank=True, null=True)),
                ("stomach", models.FloatField(blank=True, null=True)),
                ("hips", models.FloatField(blank=True, null=True)),
                ("thighs", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="daysummary",
            name="measurements",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="tracker.measurements",
            ),
        ),
    ]
