# Generated by Django 4.1.2 on 2025-03-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_measurements_daysummary_measurements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="daysummary",
            name="activity_name",
        ),
        migrations.RemoveField(
            model_name="daysummary",
            name="activity_quantity",
        ),
        migrations.RemoveField(
            model_name="daysummary",
            name="activity_unit",
        ),
        migrations.AddField(
            model_name="daysummary",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="tracker.activity",
            ),
        ),
    ]
