# Generated by Django 4.1.2 on 2025-03-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_activity_remove_daysummary_activity_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daysummary",
            name="activity",
        ),
        migrations.AddField(
            model_name="activity",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.daysummary",
            ),
        ),
    ]
