# Generated by Django 4.1.2 on 2025-03-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_remove_daysummary_activity_activity_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daysummary",
            name="was_active",
        ),
        migrations.RemoveField(
            model_name="daysummary",
            name="weight",
        ),
        migrations.AddField(
            model_name="trackerprofile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.daysummary"
            ),
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "day",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.daysummary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.trackerprofile",
                    ),
                ),
            ],
        ),
    ]
